apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  minReadySeconds: 60
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        resources:
          requests:
            cpu: "200m"
        ports:
        - containerPort: 80